### ISSUE TITLE
Put the spec in readme?

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/spec#3]
I think we should put the spec directly into README.md. It's nice to see the spec right away.

**Comment by r10s** [comment]
although currently, there is not much in the README, i would leave the spec in a separate file.
we may want to add some meta information that do not have sth. to do with the spec directly, eg. hints about how to generate a pdf from the spec.md, how to contribute etc. cmp. eg. https://github.com/autocrypt/autocrypt
